# Generated by Django 4.1.5 on 2023-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remonty', '0004_gallery_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='social_media',
            new_name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='contact',
            name='fixly',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
