# Generated by Django 4.1.5 on 2023-01-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remonty', '0006_contact_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='AboutMe',
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'o mnie', 'verbose_name_plural': 'o mnie'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategoria', 'verbose_name_plural': 'kategorie'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'kontakt', 'verbose_name_plural': 'dane kontaktowe'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'galeria zdjęć', 'verbose_name_plural': 'galeria zdjęć'},
        ),
        migrations.AlterModelOptions(
            name='servicedescription',
            options={'verbose_name_plural': 'opis usług'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'usługa', 'verbose_name_plural': 'usługi'},
        ),
    ]
